### ISSUE TITLE
Quantify agreement/overlap

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#52]
From meeting with @jinshijian and @abigailsnyder

* We can't run naive t-test on the post-hoc distributions at least as currently, b/c depends on sample size i.e. draws
* We can compute percentage overlap
* We can quantify how many sigmas out in each distribution you have to go to hit overlap region
* Given the µ and sigma of each we should be able to run a test not dependent on any sample size

**Comment by bpbond** [comment]
Supersedes #40

**Comment by bpbond** [comment]
💡 a point HAS TO BE UNDER BOTH CURVES to be in intersection

**Comment by bpbond** [comment]
@abigailsnyder will write a toy example: 100 points for each of two µ, sigmas; compute overlap after using `stat_density()` or some other tool; plot. Thanks!

**Comment by abigailsnyder** [comment]
@jinshijian @bpbond I have the toy problem ready to go but I don't appear to have repository permission to push my local branch up and open a PR. 

The write up is quite detailed and maybe not the best organized because I was figuring out some of the nuance as I went along. And because there's always more than one way to do something, especially if you decide to take a numerical heavy vs an analytical heavy approach....
Anyway, I fully expect that I fail to be clear on at least some parts and am happy to revise or meet to explain.

**Comment by jinshijian** [comment]
Hello @abigailsnyder, I have invited you as a collaborator, you need to access the invitation first. Thanks, Jinshi
